# Generated by Django 6.0.3 on 2026-03-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Например: users, reports, orders",
                        max_length=100,
                        unique=True,
                        verbose_name="Название бизнес-объекта",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Описание объекта", null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Бизнес-объект",
                "verbose_name_plural": "Бизнес-объекты",
                "db_table": "business_elements",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название", max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Введите описание", null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="Введите email", max_length=254, unique=True, verbose_name="Email"),
                ),
                ("first_name", models.CharField(help_text="Введите имя", max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(help_text="Введите фамилию", max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, help_text="Введите отчество", max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Хранится только хэш пароля", max_length=255, verbose_name="Хэш пароля"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активен ли пользователь", verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее обновление")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AccessRoleRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read", models.BooleanField(default=False, verbose_name="Чтение своих")),
                ("read_all", models.BooleanField(default=False, verbose_name="Чтение всех")),
                ("can_create", models.BooleanField(default=False, verbose_name="Создание")),
                ("update", models.BooleanField(default=False, verbose_name="Обновление своих")),
                ("update_all", models.BooleanField(default=False, verbose_name="Обновление всех")),
                ("delete", models.BooleanField(default=False, verbose_name="Удаление своих")),
                ("delete_all", models.BooleanField(default=False, verbose_name="Удаление всех")),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="auth_app.businesselement",
                        verbose_name="Бизнес-объект",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="auth_app.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило доступа",
                "verbose_name_plural": "Правила доступа",
                "db_table": "access_role_rules",
                "unique_together": {("role", "element")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата назначения")),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Выберите роль",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="auth_app.role",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Выберите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="auth_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя",
                "verbose_name_plural": "Роли пользователей",
                "db_table": "user_roles",
                "unique_together": {("user", "role")},
            },
        ),
    ]
