services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: auth-api
    ports:
      - "${APP_GUVICORN_PORT}:${APP_GUVICORN_PORT}"
    env_file:
      - .env
    depends_on:
      - auth-db
    volumes:
      - ./app/src:/app
    networks:
      - auth-network

  auth-db:
    image: postgres:17.6-alpine
    container_name: auth-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
  

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge